<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="RevolutionWeb.Default" %>

<!DOCTYPE html>

<html>
<head runat="server">
    <title>SignalR Simple Chat</title>
    <style type="text/css">
        .container {
            background-color: #99CCFF;
            border: thick solid #808080;
            padding: 20px;
            margin: 20px;
        }
    </style>
    <!--Script references.-->
    <script src="<%#RevolutionWeb.Global.JQuery%>"></script>
    <script src="<%#RevolutionWeb.Global.SignalR%>"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>

    <!--Add script to update the page and send messages.-->
    <script type="text/javascript">
        $(function () {
            // Declare a proxy to reference the hub. 
            var chat = $.connection.chatHub;
            // Create a function that the hub can call to broadcast messages.
            chat.client.broadcastMessage = function (name, message) {
                // Html encode display name and message. 
                var encodedName = $('<div />').text(name).html();
                var encodedMsg = $('<div />').text(message).html();
                // Add the message to the page. 
                $('#Discussion').append('<li><strong>' + encodedName
                    + '</strong>:&nbsp;&nbsp;' + encodedMsg + '</li>');
            };
            // Get the user name and store it to prepend to messages.
            $('#<%#nameof(DisplayName)%>').val(prompt('Enter your name:', ''));
            // Set initial focus to message input box.  
            $('#<%#nameof(Message)%>').focus();
            // Start the connection.
            $.connection.hub.start().done(function () {
                $('#<%#nameof(SendMessage)%>').click(function () {
                    // Call the Send method on the hub. 
                    chat.server.send($('#<%#nameof(DisplayName)%>').val(), $('#<%#nameof(Message)%>').val());
                    // Clear text box and reset focus for next comment. 
                    $('#<%#nameof(Message)%>').val('').focus();
                });
            });
        });
    </script>
</head>
<body>
    <div>
        <div class="container">
            <input type="text" id="Message" runat="server" />
            <input type="button" id="SendMessage" value="Send" runat="server" />
            <input type="hidden" id="DisplayName" runat="server" />
            <ul id="Discussion" runat="server">
            </ul>
        </div>

    </div>

</body>
</html>
